#!/bin/bash

homeVundle="$HOME/.vim/bundle/Vundle.vim"

# Check if you have vundle and if not, it will be installed
if [ -e $homeVundle ]; then
	echo "You have Vundle installed."
else
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	echo "Vundle installation complete."
fi

# Copies .vimrc to home directory
cp vim-config/.vimrc $HOME

vim +PluginInstall +qall

