#!/bin/bash

if [ "$EUID" != 0 ]; then
        echo "Must require sudo or root to run this script"
        exit 0
else
        echo "You are running in root"
fi

if apt --version; then
        echo "Apt is available on your system"
else
        echo "This script uses apt package manager"
        exit 0
fi

echo  "This script will install AWS Command Line Interface, are you sure you want to install it? (Y/N)"
        read input

if [ "$input" = "Y" ] || [ "$input" = "y" ]; then
        echo "Installing...."
else
        echo "AWS Command Line Interface will not be installed"
        exit 0
fi

if which aws; then
        echo "AWS seem to already exist in the directory, it will cause conflict"
        echo "Stopping Installation...."
        exit 0
else
        curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install
fi

echo "The installation is complete, run the command 'aws help' to see the list of commands"